kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-pods-binding
subjects:
- kind: User
  name: alice
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: view-pods-role
  apiGroup: rbac.authorization.k8s.io
